load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "gnmi_dump_lib",
    srcs = ["gnmi_dump.go"],
    importpath = "github.com/sonic-net/sonic-gnmi/gnmi_dump",
    visibility = ["//visibility:private"],
    deps = ["//common_utils"],
)

go_binary(
    name = "gnmi_dump",
    cgo = True,
    clinkopts = [
        "-static-libstdc++",
        "-static-libgcc",
    ],
    embed = [":gnmi_dump_lib"],
    visibility = ["//visibility:public"],
)
