load("@gazelle//:def.bzl", "gazelle")
load("@rules_pkg//:pkg.bzl", "pkg_tar")

# TODO: Add buildtools to MODULE.bazel bazel_dep
# load("@com_github_bazelbuild_buildtools//buildifier:def.bzl", "buildifier")

# gazelle:prefix github.com/sonic-net/sonic-gnmi
# gazelle:exclude patches
# gazelle:go_naming_convention import_alias

### Help Gazelle resolve sonic-mgmt-common imports to external module
# gazelle:resolve go github.com/Azure/sonic-mgmt-common/cvl @sonic-mgmt-common//cvl
# gazelle:resolve go github.com/Azure/sonic-mgmt-common/cvl/common @sonic-mgmt-common//cvl/common
# gazelle:resolve go github.com/Azure/sonic-mgmt-common/cvl/custom_validation @sonic-mgmt-common//cvl/custom_validation
# gazelle:resolve go github.com/Azure/sonic-mgmt-common/cvl/internal/util @sonic-mgmt-common//cvl/internal/util
# gazelle:resolve go github.com/Azure/sonic-mgmt-common/cvl/internal/yparser @sonic-mgmt-common//cvl/internal/yparser
# gazelle:resolve go github.com/Azure/sonic-mgmt-common/translib @sonic-mgmt-common//translib
# gazelle:resolve go github.com/Azure/sonic-mgmt-common/translib/cs @sonic-mgmt-common//translib/cs
# gazelle:resolve go github.com/Azure/sonic-mgmt-common/translib/db @sonic-mgmt-common//translib/db
# gazelle:resolve go github.com/Azure/sonic-mgmt-common/translib/internal/apis @sonic-mgmt-common//translib/internal/apis
# gazelle:resolve go github.com/Azure/sonic-mgmt-common/translib/log @sonic-mgmt-common//translib/log
# gazelle:resolve go github.com/Azure/sonic-mgmt-common/translib/ocbinds @sonic-mgmt-common//translib/ocbinds
# gazelle:resolve go github.com/Azure/sonic-mgmt-common/translib/path @sonic-mgmt-common//translib/path
# gazelle:resolve go github.com/Azure/sonic-mgmt-common/translib/platform @sonic-mgmt-common//translib/platform
# gazelle:resolve go github.com/Azure/sonic-mgmt-common/translib/tlerr @sonic-mgmt-common//translib/tlerr
# gazelle:resolve go github.com/Azure/sonic-mgmt-common/translib/transformer @sonic-mgmt-common//translib/transformer
# gazelle:resolve go github.com/Azure/sonic-mgmt-common/translib/utils @sonic-mgmt-common//translib/utils

### Help Gazelle resolve external proto files

# gazelle:resolve go          google.golang.org/genproto/googleapis/rpc/status @org_golang_google_genproto_googleapis_rpc//status
# gazelle:resolve proto go    google/rpc/status.proto                          @org_golang_google_genproto_googleapis_rpc//status
# gazelle:resolve proto proto google/rpc/status.proto                          @googleapis//google/rpc:status_proto
# gazelle:resolve proto go    github.com/openconfig/gnoi/types/types.proto     @com_github_openconfig_gnoi//types
# gazelle:resolve proto proto github.com/openconfig/gnoi/types/types.proto     @com_github_openconfig_gnoi//types:types_proto
# gazelle:resolve proto go    github.com/openconfig/ygot/proto/yext/yext.proto @com_github_openconfig_ygot//proto/yext:yext_go_proto
# gazelle:resolve proto proto github.com/openconfig/ygot/proto/yext/yext.proto @com_github_openconfig_ygot//proto/yext:yext_proto
# gazelle:resolve proto go    github.com/openconfig/gnmi/proto/gnmi/gnmi.proto @com_github_openconfig_gnmi//proto/gnmi
# gazelle:resolve proto proto github.com/openconfig/gnmi/proto/gnmi/gnmi.proto @com_github_openconfig_gnmi//proto/gnmi:gnmi_proto
# gazelle:resolve proto go    github.com/gogo/protobuf/gogoproto/gogo.proto    @com_github_gogo_protobuf//gogoproto

gazelle(name = "gazelle")

#bazel build :gazelle-update-repos
gazelle(
    name = "gazelle-update-repos",
    args = [
        "-from_file=go.mod",
        "-to_macro=deps.bzl%go_dependencies",
        "-prune",
    ],
    command = "update-repos",
)

# TODO: Add buildtools to MODULE.bazel bazel_dep
# buildifier(
#     name = "buildifier",
# )

# Use this to generate a text file with a tree diagram of all YANG models
# used by UMF.
alias(
    name = "whole-yang-tree-txt",
    actual = "@sonic-mgmt-common//models/yang:yang-tree",
)

# A shortcut to build a Docker image that is used for component testing.
alias(
    name = "gnmi_server_test_image",
    actual = "//gnmi_server:gnmi_server_test_image",
)

# A shortcut to build a Docker image that is used for debugging UMF.
alias(
    name = "gnmi_server_debug_image",
    actual = "//gnmi_server:gnmi_server_debug_image",
)

# Consolidated package containing all gNMI binaries
pkg_tar(
    name = "gnmi_binaries",
    srcs = [
        "//telemetry:telemetry",
        "//gnmi_dump:gnmi_dump",
        "//gnoi_client:gnoi_client",
        "//dialout/dialout_client_cli:dialout_client_cli",
    ],
    mode = "0755",
    package_dir = "/usr/sbin",
    visibility = ["//visibility:public"],
)

# Export libyang runtime libraries for container packaging
# These need to be packaged into OCI containers that run gNMI binaries
filegroup(
    name = "libyang_shared_libs",
    srcs = ["@com_github_cesnet_libyang//:shared_libs"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "libyang_extension_plugins",
    srcs = ["@com_github_cesnet_libyang//:extension_plugins"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "libyang_user_type_plugins",
    srcs = ["@com_github_cesnet_libyang//:user_type_plugins"],
    visibility = ["//visibility:public"],
)

