module(
    name = "sonic-gnmi",
    version = "0.0.0",
)

bazel_dep(name = "platforms", version = "0.0.11")
bazel_dep(name = "rules_pkg", version = "1.0.1")

# TODO BL: Check if this version works. Original uses 4.6.0, but it's not in the BCR
bazel_dep(name = "rules_proto_grpc", version = "5.0.0")
bazel_dep(name = "rules_go", version = "0.60.0", repo_name = "io_bazel_rules_go")
# TODO BL: Originally this is commit fe771208f21a28e11507352faf03098244d42f0c,
# check if we need to change
bazel_dep(name = "googleapis", version = "0.0.0-20251104-53af3b72")
# TODO BL: We may need this
# bazel_dep(name = "googleapis-go", version = "1.0.0")
bazel_dep(name = "sonic-mgmt-common", version = "1.0.0", repo_name = "sonic_mgmt_common")

go_sdk = use_extension("@io_bazel_rules_go//go:extensions.bzl", "go_sdk")
# TODO BL: We may need to upgrade, the PR has a newer version
# go_sdk.download(version = "1.24.5")
go_sdk.download(version = "1.22.4")

bazel_dep(name = "rules_distroless", version = "0.0.0")
git_override(
    module_name = "rules_distroless",
    commit = "ebfd74a2e07b83235e064bb63ace98a1a5223e02",
    remote = "https://github.com/bazel-contrib/rules_distroless",
)

# TODO BL: we may need to upgrade, the branch has a newer version
# bazel_dep(name = "rules_python", version = "1.6.3")
# # Pin rules_python to 1.6.3 for stability. With protoc-gen-validate@1.3.0 pinned above,
# # newer versions of rules_python may now be compatible - this can be tested later.
# # TODO BL: If we do end up pinning, we need to find a way to propagate this.
# single_version_override(
#     module_name = "rules_python",
#     version = "1.6.3",
# )
# python = use_extension("@rules_python//python/extensions:python.bzl", "python")
# python.toolchain(
#     python_version = "3.11",
# )
bazel_dep(name = "rules_python", version = "0.10.2")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    python_version = "3.09",
)

# TODO BL: install pip requirements from //third_party/pip:requirements.txt
# From WORKSPACE
# pip_install(
#     name = "pip",
#     python_interpreter_target = interpreter,
#     requirements = "//third_party/pip:requirements.txt",
# )
#

bazel_dep(name = "libyang", version = "1.0.73")
# TODO BL: adjust dependencies to libyang
# TODO BL: We oariginally depend on libyang v1.0.255, not sure if it's relevant.

apt = use_extension("@rules_distroless//apt:extensions.bzl", "apt")
apt.sources_list(
    architectures = ["amd64"],
    components = ["main"],
    suites = [
        "bookworm",
        "bookworm-updates",
    ],
    uris = ["https://snapshot.debian.org/archive/debian/20251001T023456Z"],
)
apt.sources_list(
    architectures = ["amd64"],
    components = ["main"],
    suites = ["bookworm-security"],
    uris = ["https://snapshot.debian.org/archive/debian-security/20251001T023456Z"],
)
apt.install(
    dependency_set = "bookworm",
    packages = [
        # sonic-gnmi specific packages
        
        # TODO BL: Adjust dpeendnecies on @pcre_archive to point to @bookworm//:libpcre3 or -dev
        "libpcre3",
        "libpcre3-dev",
        # "libpam0g",
        # "libpam0g-dev",
        # "libusb-1.0-0",
        # "libusb-1.0-0-dev",
        # # libudev is needed by libusb
        # "libudev1",
        # "libudev-dev",
        # # Boost libraries (thread and system for sonic-gnmi, base + serialization for sonic-swss-common)
        # "libboost-dev",
        # "libboost-serialization-dev",
        # "libboost-thread-dev",
        # "libboost-system-dev",
        # # Python 3.11 for sonic_data_client
        # "libpython3.11-dev",
        # "python3.11-dev",
        # # crypt.h needed by Python headers
        # "libcrypt-dev",
    ],
    suites = [
        "bookworm",
        "bookworm-updates",
        "bookworm-security",
    ],
)
apt.lock(into = ":packages.lock")
use_repo(apt, "bookworm")

bazel_dep(name = "gazelle", version = "0.46.0")
# Go dependencies via gazelle's go_deps extension
go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")


# TODO BL: Not migrated yet:
# - Buildimage, for the yang models, which I'm not sure we need beacuse nothing depends on that one target at the root.
# - swsscommon, which I'm not sure we need
# - json
# git_repository(
#     name = "com_github_nlohmann_json",
#     # Current tip of "develop" branch as of Nov-2023.  Using this commit since
#     # the last release is quite old and does not contain bazel support.
#     commit = "6eab7a2b187b10b2494e39c1961750bfd1bda500",
#     remote = "https://github.com/nlohmann/json",
# )

