// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: gnmi_sonic/umf_debug_info.proto

package gnmi_sonic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mode of subscription made by the client.
type GnmiSubscriptionClientInfo_Mode int32

const (
	GnmiSubscriptionClientInfo_MODE_UNKNOWN GnmiSubscriptionClientInfo_Mode = 0 // This is the mode used when the subscribe request has
	// not been received by UMF yet from the client.
	GnmiSubscriptionClientInfo_MODE_STREAM GnmiSubscriptionClientInfo_Mode = 1
	GnmiSubscriptionClientInfo_MODE_ONCE   GnmiSubscriptionClientInfo_Mode = 2
	GnmiSubscriptionClientInfo_MODE_POLL   GnmiSubscriptionClientInfo_Mode = 3
)

// Enum value maps for GnmiSubscriptionClientInfo_Mode.
var (
	GnmiSubscriptionClientInfo_Mode_name = map[int32]string{
		0: "MODE_UNKNOWN",
		1: "MODE_STREAM",
		2: "MODE_ONCE",
		3: "MODE_POLL",
	}
	GnmiSubscriptionClientInfo_Mode_value = map[string]int32{
		"MODE_UNKNOWN": 0,
		"MODE_STREAM":  1,
		"MODE_ONCE":    2,
		"MODE_POLL":    3,
	}
)

func (x GnmiSubscriptionClientInfo_Mode) Enum() *GnmiSubscriptionClientInfo_Mode {
	p := new(GnmiSubscriptionClientInfo_Mode)
	*p = x
	return p
}

func (x GnmiSubscriptionClientInfo_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GnmiSubscriptionClientInfo_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_gnmi_sonic_umf_debug_info_proto_enumTypes[0].Descriptor()
}

func (GnmiSubscriptionClientInfo_Mode) Type() protoreflect.EnumType {
	return &file_gnmi_sonic_umf_debug_info_proto_enumTypes[0]
}

func (x GnmiSubscriptionClientInfo_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GnmiSubscriptionClientInfo_Mode.Descriptor instead.
func (GnmiSubscriptionClientInfo_Mode) EnumDescriptor() ([]byte, []int) {
	return file_gnmi_sonic_umf_debug_info_proto_rawDescGZIP(), []int{0, 0}
}

type GnmiSubscriptionClientInfo_SubMode int32

const (
	GnmiSubscriptionClientInfo_SUB_MODE_UNKNOWN GnmiSubscriptionClientInfo_SubMode = 0 // This is the sub mode used when the subscription
	// mode is not STREAM or when
	// the subscribe request has not been received by UMF yet.
	GnmiSubscriptionClientInfo_SUB_MODE_ON_CHANGE   GnmiSubscriptionClientInfo_SubMode = 1 // The client uses ON_CHANGE sub mode for one or more paths.
	GnmiSubscriptionClientInfo_SUB_MODE_SAMPLE_ONLY GnmiSubscriptionClientInfo_SubMode = 2 // The client uses SAMPLE sub mode for all paths.
)

// Enum value maps for GnmiSubscriptionClientInfo_SubMode.
var (
	GnmiSubscriptionClientInfo_SubMode_name = map[int32]string{
		0: "SUB_MODE_UNKNOWN",
		1: "SUB_MODE_ON_CHANGE",
		2: "SUB_MODE_SAMPLE_ONLY",
	}
	GnmiSubscriptionClientInfo_SubMode_value = map[string]int32{
		"SUB_MODE_UNKNOWN":     0,
		"SUB_MODE_ON_CHANGE":   1,
		"SUB_MODE_SAMPLE_ONLY": 2,
	}
)

func (x GnmiSubscriptionClientInfo_SubMode) Enum() *GnmiSubscriptionClientInfo_SubMode {
	p := new(GnmiSubscriptionClientInfo_SubMode)
	*p = x
	return p
}

func (x GnmiSubscriptionClientInfo_SubMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GnmiSubscriptionClientInfo_SubMode) Descriptor() protoreflect.EnumDescriptor {
	return file_gnmi_sonic_umf_debug_info_proto_enumTypes[1].Descriptor()
}

func (GnmiSubscriptionClientInfo_SubMode) Type() protoreflect.EnumType {
	return &file_gnmi_sonic_umf_debug_info_proto_enumTypes[1]
}

func (x GnmiSubscriptionClientInfo_SubMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GnmiSubscriptionClientInfo_SubMode.Descriptor instead.
func (GnmiSubscriptionClientInfo_SubMode) EnumDescriptor() ([]byte, []int) {
	return file_gnmi_sonic_umf_debug_info_proto_rawDescGZIP(), []int{0, 1}
}

// GnmiSubscriptionClientInfo contains the subscription information of all
// clients to UMF.
type GnmiSubscriptionClientInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The IP address used by the gNMI client to connect to UMF.
	IpAddress string `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// The TCP port used by the gNMI client to connect to UMF.
	TcpSourcePort uint64 `protobuf:"varint,2,opt,name=tcp_source_port,json=tcpSourcePort,proto3" json:"tcp_source_port,omitempty"`
	// Describes the subscription mode used by the client.
	SubscriptionMode GnmiSubscriptionClientInfo_Mode `protobuf:"varint,3,opt,name=subscription_mode,json=subscriptionMode,proto3,enum=GnmiSubscriptionClientInfo_Mode" json:"subscription_mode,omitempty"`
	// Describes the subscription sub mode used by the client.
	SubscriptionSubMode GnmiSubscriptionClientInfo_SubMode `protobuf:"varint,4,opt,name=subscription_sub_mode,json=subscriptionSubMode,proto3,enum=GnmiSubscriptionClientInfo_SubMode" json:"subscription_sub_mode,omitempty"`
	// The time the subscription was received.
	SubscriptionStart *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=subscription_start,json=subscriptionStart,proto3" json:"subscription_start,omitempty"`
	// The time the UMF server sent the sync response.
	SyncResponseTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=sync_response_time,json=syncResponseTime,proto3" json:"sync_response_time,omitempty"`
	// The current depth of the RPC queue.
	CurrentQueueDepth uint64 `protobuf:"varint,7,opt,name=current_queue_depth,json=currentQueueDepth,proto3" json:"current_queue_depth,omitempty"`
	// The max depth of the RPC queue.
	MaxQueueDepth uint64 `protobuf:"varint,8,opt,name=max_queue_depth,json=maxQueueDepth,proto3" json:"max_queue_depth,omitempty"`
	// The tick latency info for each interval in the subscription.
	TickLatencyInfo []*TickLatencyInfo `protobuf:"bytes,9,rep,name=tick_latency_info,json=tickLatencyInfo,proto3" json:"tick_latency_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GnmiSubscriptionClientInfo) Reset() {
	*x = GnmiSubscriptionClientInfo{}
	mi := &file_gnmi_sonic_umf_debug_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GnmiSubscriptionClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GnmiSubscriptionClientInfo) ProtoMessage() {}

func (x *GnmiSubscriptionClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gnmi_sonic_umf_debug_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GnmiSubscriptionClientInfo.ProtoReflect.Descriptor instead.
func (*GnmiSubscriptionClientInfo) Descriptor() ([]byte, []int) {
	return file_gnmi_sonic_umf_debug_info_proto_rawDescGZIP(), []int{0}
}

func (x *GnmiSubscriptionClientInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *GnmiSubscriptionClientInfo) GetTcpSourcePort() uint64 {
	if x != nil {
		return x.TcpSourcePort
	}
	return 0
}

func (x *GnmiSubscriptionClientInfo) GetSubscriptionMode() GnmiSubscriptionClientInfo_Mode {
	if x != nil {
		return x.SubscriptionMode
	}
	return GnmiSubscriptionClientInfo_MODE_UNKNOWN
}

func (x *GnmiSubscriptionClientInfo) GetSubscriptionSubMode() GnmiSubscriptionClientInfo_SubMode {
	if x != nil {
		return x.SubscriptionSubMode
	}
	return GnmiSubscriptionClientInfo_SUB_MODE_UNKNOWN
}

func (x *GnmiSubscriptionClientInfo) GetSubscriptionStart() *timestamppb.Timestamp {
	if x != nil {
		return x.SubscriptionStart
	}
	return nil
}

func (x *GnmiSubscriptionClientInfo) GetSyncResponseTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SyncResponseTime
	}
	return nil
}

func (x *GnmiSubscriptionClientInfo) GetCurrentQueueDepth() uint64 {
	if x != nil {
		return x.CurrentQueueDepth
	}
	return 0
}

func (x *GnmiSubscriptionClientInfo) GetMaxQueueDepth() uint64 {
	if x != nil {
		return x.MaxQueueDepth
	}
	return 0
}

func (x *GnmiSubscriptionClientInfo) GetTickLatencyInfo() []*TickLatencyInfo {
	if x != nil {
		return x.TickLatencyInfo
	}
	return nil
}

type TickLatencyInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sample interval that these latencies correspond to.
	Interval uint64 `protobuf:"varint,1,opt,name=interval,proto3" json:"interval,omitempty"`
	// The minimum latency for handling a single tick of this interval.
	MinLatency *durationpb.Duration `protobuf:"bytes,2,opt,name=min_latency,json=minLatency,proto3" json:"min_latency,omitempty"`
	// The mean latency for handling a single tick of this interval.
	MeanLatency *durationpb.Duration `protobuf:"bytes,3,opt,name=mean_latency,json=meanLatency,proto3" json:"mean_latency,omitempty"`
	// The max latency for handling a single tick of this interval.
	MaxLatency    *durationpb.Duration `protobuf:"bytes,4,opt,name=max_latency,json=maxLatency,proto3" json:"max_latency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickLatencyInfo) Reset() {
	*x = TickLatencyInfo{}
	mi := &file_gnmi_sonic_umf_debug_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickLatencyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickLatencyInfo) ProtoMessage() {}

func (x *TickLatencyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gnmi_sonic_umf_debug_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickLatencyInfo.ProtoReflect.Descriptor instead.
func (*TickLatencyInfo) Descriptor() ([]byte, []int) {
	return file_gnmi_sonic_umf_debug_info_proto_rawDescGZIP(), []int{1}
}

func (x *TickLatencyInfo) GetInterval() uint64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *TickLatencyInfo) GetMinLatency() *durationpb.Duration {
	if x != nil {
		return x.MinLatency
	}
	return nil
}

func (x *TickLatencyInfo) GetMeanLatency() *durationpb.Duration {
	if x != nil {
		return x.MeanLatency
	}
	return nil
}

func (x *TickLatencyInfo) GetMaxLatency() *durationpb.Duration {
	if x != nil {
		return x.MaxLatency
	}
	return nil
}

// GnmiRequestTimingInfo contains timestamps for when a Get request
// started and ended processing.
type GnmiRequestTimingInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The IP address used by the gNMI client to connect to UMF.
	IpAddress string `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// The TCP port used by the gNMI client to connect to UMF.
	TcpSourcePort uint64 `protobuf:"varint,2,opt,name=tcp_source_port,json=tcpSourcePort,proto3" json:"tcp_source_port,omitempty"`
	// The time that the UMF server started processing the request.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// The time that the UMF server finished processing the request.
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GnmiRequestTimingInfo) Reset() {
	*x = GnmiRequestTimingInfo{}
	mi := &file_gnmi_sonic_umf_debug_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GnmiRequestTimingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GnmiRequestTimingInfo) ProtoMessage() {}

func (x *GnmiRequestTimingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gnmi_sonic_umf_debug_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GnmiRequestTimingInfo.ProtoReflect.Descriptor instead.
func (*GnmiRequestTimingInfo) Descriptor() ([]byte, []int) {
	return file_gnmi_sonic_umf_debug_info_proto_rawDescGZIP(), []int{2}
}

func (x *GnmiRequestTimingInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *GnmiRequestTimingInfo) GetTcpSourcePort() uint64 {
	if x != nil {
		return x.TcpSourcePort
	}
	return 0
}

func (x *GnmiRequestTimingInfo) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GnmiRequestTimingInfo) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// DbClientCounters contains stats for UMF's connections to Redis.
type DbCounters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of transactional Redis clients open in UMF currently.
	CurrentTransactionalClients uint32 `protobuf:"varint,1,opt,name=current_transactional_clients,json=currentTransactionalClients,proto3" json:"current_transactional_clients,omitempty"`
	// The number of requested Redis clients that use a connection pool.
	TotalPoolClientsRequested uint64 `protobuf:"varint,2,opt,name=total_pool_clients_requested,json=totalPoolClientsRequested,proto3" json:"total_pool_clients_requested,omitempty"`
	// The number of requested Redis clients that are used for transactions.
	TotalTransactionalClientsRequested uint64 `protobuf:"varint,3,opt,name=total_transactional_clients_requested,json=totalTransactionalClientsRequested,proto3" json:"total_transactional_clients_requested,omitempty"`
	// The connection pool stats per Redis database.
	DbPoolStats   []*DbConnectionPoolStats `protobuf:"bytes,4,rep,name=db_pool_stats,json=dbPoolStats,proto3" json:"db_pool_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DbCounters) Reset() {
	*x = DbCounters{}
	mi := &file_gnmi_sonic_umf_debug_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbCounters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbCounters) ProtoMessage() {}

func (x *DbCounters) ProtoReflect() protoreflect.Message {
	mi := &file_gnmi_sonic_umf_debug_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbCounters.ProtoReflect.Descriptor instead.
func (*DbCounters) Descriptor() ([]byte, []int) {
	return file_gnmi_sonic_umf_debug_info_proto_rawDescGZIP(), []int{3}
}

func (x *DbCounters) GetCurrentTransactionalClients() uint32 {
	if x != nil {
		return x.CurrentTransactionalClients
	}
	return 0
}

func (x *DbCounters) GetTotalPoolClientsRequested() uint64 {
	if x != nil {
		return x.TotalPoolClientsRequested
	}
	return 0
}

func (x *DbCounters) GetTotalTransactionalClientsRequested() uint64 {
	if x != nil {
		return x.TotalTransactionalClientsRequested
	}
	return 0
}

func (x *DbCounters) GetDbPoolStats() []*DbConnectionPoolStats {
	if x != nil {
		return x.DbPoolStats
	}
	return nil
}

// The connection pool stats for a Redis database.
type DbConnectionPoolStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The DB name.
	DbName string `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	// The number of times a free connection was found in the pool.
	Hits uint32 `protobuf:"varint,2,opt,name=hits,proto3" json:"hits,omitempty"`
	// The number of times a free connection was not found in the pool.
	Misses uint32 `protobuf:"varint,3,opt,name=misses,proto3" json:"misses,omitempty"`
	// The number of times a wait timeout occurred.
	Timeouts uint32 `protobuf:"varint,4,opt,name=timeouts,proto3" json:"timeouts,omitempty"`
	// The number of total active connections in the pool.
	TotalActiveConnections uint32 `protobuf:"varint,5,opt,name=total_active_connections,json=totalActiveConnections,proto3" json:"total_active_connections,omitempty"`
	// The number of idle connections in the pool.
	IdleConnections uint32 `protobuf:"varint,6,opt,name=idle_connections,json=idleConnections,proto3" json:"idle_connections,omitempty"`
	// The number of stale connections removed from the pool.
	StaleConnections uint32 `protobuf:"varint,7,opt,name=stale_connections,json=staleConnections,proto3" json:"stale_connections,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DbConnectionPoolStats) Reset() {
	*x = DbConnectionPoolStats{}
	mi := &file_gnmi_sonic_umf_debug_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbConnectionPoolStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbConnectionPoolStats) ProtoMessage() {}

func (x *DbConnectionPoolStats) ProtoReflect() protoreflect.Message {
	mi := &file_gnmi_sonic_umf_debug_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbConnectionPoolStats.ProtoReflect.Descriptor instead.
func (*DbConnectionPoolStats) Descriptor() ([]byte, []int) {
	return file_gnmi_sonic_umf_debug_info_proto_rawDescGZIP(), []int{4}
}

func (x *DbConnectionPoolStats) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *DbConnectionPoolStats) GetHits() uint32 {
	if x != nil {
		return x.Hits
	}
	return 0
}

func (x *DbConnectionPoolStats) GetMisses() uint32 {
	if x != nil {
		return x.Misses
	}
	return 0
}

func (x *DbConnectionPoolStats) GetTimeouts() uint32 {
	if x != nil {
		return x.Timeouts
	}
	return 0
}

func (x *DbConnectionPoolStats) GetTotalActiveConnections() uint32 {
	if x != nil {
		return x.TotalActiveConnections
	}
	return 0
}

func (x *DbConnectionPoolStats) GetIdleConnections() uint32 {
	if x != nil {
		return x.IdleConnections
	}
	return 0
}

func (x *DbConnectionPoolStats) GetStaleConnections() uint32 {
	if x != nil {
		return x.StaleConnections
	}
	return 0
}

// Go Metrics that are read from the runtime. See https://pkg.go.dev/runtime/metrics.
type GoRuntimeMetric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*GoRuntimeMetric_Uint64Val
	//	*GoRuntimeMetric_DoubleVal
	Value         isGoRuntimeMetric_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoRuntimeMetric) Reset() {
	*x = GoRuntimeMetric{}
	mi := &file_gnmi_sonic_umf_debug_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoRuntimeMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoRuntimeMetric) ProtoMessage() {}

func (x *GoRuntimeMetric) ProtoReflect() protoreflect.Message {
	mi := &file_gnmi_sonic_umf_debug_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoRuntimeMetric.ProtoReflect.Descriptor instead.
func (*GoRuntimeMetric) Descriptor() ([]byte, []int) {
	return file_gnmi_sonic_umf_debug_info_proto_rawDescGZIP(), []int{5}
}

func (x *GoRuntimeMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoRuntimeMetric) GetValue() isGoRuntimeMetric_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GoRuntimeMetric) GetUint64Val() uint64 {
	if x != nil {
		if x, ok := x.Value.(*GoRuntimeMetric_Uint64Val); ok {
			return x.Uint64Val
		}
	}
	return 0
}

func (x *GoRuntimeMetric) GetDoubleVal() float64 {
	if x != nil {
		if x, ok := x.Value.(*GoRuntimeMetric_DoubleVal); ok {
			return x.DoubleVal
		}
	}
	return 0
}

type isGoRuntimeMetric_Value interface {
	isGoRuntimeMetric_Value()
}

type GoRuntimeMetric_Uint64Val struct {
	Uint64Val uint64 `protobuf:"varint,2,opt,name=uint64_val,json=uint64Val,proto3,oneof"`
}

type GoRuntimeMetric_DoubleVal struct {
	DoubleVal float64 `protobuf:"fixed64,3,opt,name=double_val,json=doubleVal,proto3,oneof"`
}

func (*GoRuntimeMetric_Uint64Val) isGoRuntimeMetric_Value() {}

func (*GoRuntimeMetric_DoubleVal) isGoRuntimeMetric_Value() {}

// The RPC limits stats from Connection Manager.
type ConnectionManagerStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The limit for active streaming RPCs.
	StreamingRpcThreshold uint32 `protobuf:"varint,1,opt,name=streaming_rpc_threshold,json=streamingRpcThreshold,proto3" json:"streaming_rpc_threshold,omitempty"`
	// The number of active streaming RPCs.
	ActiveStreamingRpc uint32 `protobuf:"varint,2,opt,name=active_streaming_rpc,json=activeStreamingRpc,proto3" json:"active_streaming_rpc,omitempty"`
	// The total number of rejected Streaming RPCs.
	RejectedStreamingRpc uint32 `protobuf:"varint,3,opt,name=rejected_streaming_rpc,json=rejectedStreamingRpc,proto3" json:"rejected_streaming_rpc,omitempty"`
	// The limit of active unary RPCs.
	UnaryRpcThreshold uint32 `protobuf:"varint,4,opt,name=unary_rpc_threshold,json=unaryRpcThreshold,proto3" json:"unary_rpc_threshold,omitempty"`
	// The number of active unary RPCs.
	ActiveUnaryRpc uint32 `protobuf:"varint,5,opt,name=active_unary_rpc,json=activeUnaryRpc,proto3" json:"active_unary_rpc,omitempty"`
	// The total number of rejected Unary RPCs.
	RejectedUnaryRpc uint32 `protobuf:"varint,6,opt,name=rejected_unary_rpc,json=rejectedUnaryRpc,proto3" json:"rejected_unary_rpc,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectionManagerStats) Reset() {
	*x = ConnectionManagerStats{}
	mi := &file_gnmi_sonic_umf_debug_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionManagerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionManagerStats) ProtoMessage() {}

func (x *ConnectionManagerStats) ProtoReflect() protoreflect.Message {
	mi := &file_gnmi_sonic_umf_debug_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionManagerStats.ProtoReflect.Descriptor instead.
func (*ConnectionManagerStats) Descriptor() ([]byte, []int) {
	return file_gnmi_sonic_umf_debug_info_proto_rawDescGZIP(), []int{6}
}

func (x *ConnectionManagerStats) GetStreamingRpcThreshold() uint32 {
	if x != nil {
		return x.StreamingRpcThreshold
	}
	return 0
}

func (x *ConnectionManagerStats) GetActiveStreamingRpc() uint32 {
	if x != nil {
		return x.ActiveStreamingRpc
	}
	return 0
}

func (x *ConnectionManagerStats) GetRejectedStreamingRpc() uint32 {
	if x != nil {
		return x.RejectedStreamingRpc
	}
	return 0
}

func (x *ConnectionManagerStats) GetUnaryRpcThreshold() uint32 {
	if x != nil {
		return x.UnaryRpcThreshold
	}
	return 0
}

func (x *ConnectionManagerStats) GetActiveUnaryRpc() uint32 {
	if x != nil {
		return x.ActiveUnaryRpc
	}
	return 0
}

func (x *ConnectionManagerStats) GetRejectedUnaryRpc() uint32 {
	if x != nil {
		return x.RejectedUnaryRpc
	}
	return 0
}

// UmfDebugInfo contains all debug information of interest collected from UMF.
type UmfDebugInfo struct {
	state                  protoimpl.MessageState        `protogen:"open.v1"`
	SubscriptionClientInfo []*GnmiSubscriptionClientInfo `protobuf:"bytes,1,rep,name=subscription_client_info,json=subscriptionClientInfo,proto3" json:"subscription_client_info,omitempty"`
	GetRequestTimingInfo   []*GnmiRequestTimingInfo      `protobuf:"bytes,2,rep,name=get_request_timing_info,json=getRequestTimingInfo,proto3" json:"get_request_timing_info,omitempty"`
	DbCounters             *DbCounters                   `protobuf:"bytes,3,opt,name=db_counters,json=dbCounters,proto3" json:"db_counters,omitempty"`
	// The number of active goroutines in the telemetry process.
	NumGoroutines          uint32                   `protobuf:"varint,4,opt,name=num_goroutines,json=numGoroutines,proto3" json:"num_goroutines,omitempty"`
	GoRuntimeMetric        []*GoRuntimeMetric       `protobuf:"bytes,5,rep,name=go_runtime_metric,json=goRuntimeMetric,proto3" json:"go_runtime_metric,omitempty"`
	ConnectionManagerStats *ConnectionManagerStats  `protobuf:"bytes,6,opt,name=connection_manager_stats,json=connectionManagerStats,proto3" json:"connection_manager_stats,omitempty"`
	SetRequestTimingInfo   []*GnmiRequestTimingInfo `protobuf:"bytes,7,rep,name=set_request_timing_info,json=setRequestTimingInfo,proto3" json:"set_request_timing_info,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UmfDebugInfo) Reset() {
	*x = UmfDebugInfo{}
	mi := &file_gnmi_sonic_umf_debug_info_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UmfDebugInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UmfDebugInfo) ProtoMessage() {}

func (x *UmfDebugInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gnmi_sonic_umf_debug_info_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UmfDebugInfo.ProtoReflect.Descriptor instead.
func (*UmfDebugInfo) Descriptor() ([]byte, []int) {
	return file_gnmi_sonic_umf_debug_info_proto_rawDescGZIP(), []int{7}
}

func (x *UmfDebugInfo) GetSubscriptionClientInfo() []*GnmiSubscriptionClientInfo {
	if x != nil {
		return x.SubscriptionClientInfo
	}
	return nil
}

func (x *UmfDebugInfo) GetGetRequestTimingInfo() []*GnmiRequestTimingInfo {
	if x != nil {
		return x.GetRequestTimingInfo
	}
	return nil
}

func (x *UmfDebugInfo) GetDbCounters() *DbCounters {
	if x != nil {
		return x.DbCounters
	}
	return nil
}

func (x *UmfDebugInfo) GetNumGoroutines() uint32 {
	if x != nil {
		return x.NumGoroutines
	}
	return 0
}

func (x *UmfDebugInfo) GetGoRuntimeMetric() []*GoRuntimeMetric {
	if x != nil {
		return x.GoRuntimeMetric
	}
	return nil
}

func (x *UmfDebugInfo) GetConnectionManagerStats() *ConnectionManagerStats {
	if x != nil {
		return x.ConnectionManagerStats
	}
	return nil
}

func (x *UmfDebugInfo) GetSetRequestTimingInfo() []*GnmiRequestTimingInfo {
	if x != nil {
		return x.SetRequestTimingInfo
	}
	return nil
}

var File_gnmi_sonic_umf_debug_info_proto protoreflect.FileDescriptor

const file_gnmi_sonic_umf_debug_info_proto_rawDesc = "" +
	"\n" +
	"\x1fgnmi_sonic/umf_debug_info.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xd2\x05\n" +
	"\x1aGnmiSubscriptionClientInfo\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12&\n" +
	"\x0ftcp_source_port\x18\x02 \x01(\x04R\rtcpSourcePort\x12M\n" +
	"\x11subscription_mode\x18\x03 \x01(\x0e2 .GnmiSubscriptionClientInfo.ModeR\x10subscriptionMode\x12W\n" +
	"\x15subscription_sub_mode\x18\x04 \x01(\x0e2#.GnmiSubscriptionClientInfo.SubModeR\x13subscriptionSubMode\x12I\n" +
	"\x12subscription_start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x11subscriptionStart\x12H\n" +
	"\x12sync_response_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x10syncResponseTime\x12.\n" +
	"\x13current_queue_depth\x18\a \x01(\x04R\x11currentQueueDepth\x12&\n" +
	"\x0fmax_queue_depth\x18\b \x01(\x04R\rmaxQueueDepth\x12<\n" +
	"\x11tick_latency_info\x18\t \x03(\v2\x10.TickLatencyInfoR\x0ftickLatencyInfo\"G\n" +
	"\x04Mode\x12\x10\n" +
	"\fMODE_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vMODE_STREAM\x10\x01\x12\r\n" +
	"\tMODE_ONCE\x10\x02\x12\r\n" +
	"\tMODE_POLL\x10\x03\"Q\n" +
	"\aSubMode\x12\x14\n" +
	"\x10SUB_MODE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12SUB_MODE_ON_CHANGE\x10\x01\x12\x18\n" +
	"\x14SUB_MODE_SAMPLE_ONLY\x10\x02\"\xe3\x01\n" +
	"\x0fTickLatencyInfo\x12\x1a\n" +
	"\binterval\x18\x01 \x01(\x04R\binterval\x12:\n" +
	"\vmin_latency\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"minLatency\x12<\n" +
	"\fmean_latency\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vmeanLatency\x12:\n" +
	"\vmax_latency\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"maxLatency\"\xd0\x01\n" +
	"\x15GnmiRequestTimingInfo\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12&\n" +
	"\x0ftcp_source_port\x18\x02 \x01(\x04R\rtcpSourcePort\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xa0\x02\n" +
	"\n" +
	"DbCounters\x12B\n" +
	"\x1dcurrent_transactional_clients\x18\x01 \x01(\rR\x1bcurrentTransactionalClients\x12?\n" +
	"\x1ctotal_pool_clients_requested\x18\x02 \x01(\x04R\x19totalPoolClientsRequested\x12Q\n" +
	"%total_transactional_clients_requested\x18\x03 \x01(\x04R\"totalTransactionalClientsRequested\x12:\n" +
	"\rdb_pool_stats\x18\x04 \x03(\v2\x16.DbConnectionPoolStatsR\vdbPoolStats\"\x8a\x02\n" +
	"\x15DbConnectionPoolStats\x12\x17\n" +
	"\adb_name\x18\x01 \x01(\tR\x06dbName\x12\x12\n" +
	"\x04hits\x18\x02 \x01(\rR\x04hits\x12\x16\n" +
	"\x06misses\x18\x03 \x01(\rR\x06misses\x12\x1a\n" +
	"\btimeouts\x18\x04 \x01(\rR\btimeouts\x128\n" +
	"\x18total_active_connections\x18\x05 \x01(\rR\x16totalActiveConnections\x12)\n" +
	"\x10idle_connections\x18\x06 \x01(\rR\x0fidleConnections\x12+\n" +
	"\x11stale_connections\x18\a \x01(\rR\x10staleConnections\"p\n" +
	"\x0fGoRuntimeMetric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\n" +
	"uint64_val\x18\x02 \x01(\x04H\x00R\tuint64Val\x12\x1f\n" +
	"\n" +
	"double_val\x18\x03 \x01(\x01H\x00R\tdoubleValB\a\n" +
	"\x05value\"\xc0\x02\n" +
	"\x16ConnectionManagerStats\x126\n" +
	"\x17streaming_rpc_threshold\x18\x01 \x01(\rR\x15streamingRpcThreshold\x120\n" +
	"\x14active_streaming_rpc\x18\x02 \x01(\rR\x12activeStreamingRpc\x124\n" +
	"\x16rejected_streaming_rpc\x18\x03 \x01(\rR\x14rejectedStreamingRpc\x12.\n" +
	"\x13unary_rpc_threshold\x18\x04 \x01(\rR\x11unaryRpcThreshold\x12(\n" +
	"\x10active_unary_rpc\x18\x05 \x01(\rR\x0eactiveUnaryRpc\x12,\n" +
	"\x12rejected_unary_rpc\x18\x06 \x01(\rR\x10rejectedUnaryRpc\"\xe9\x03\n" +
	"\fUmfDebugInfo\x12U\n" +
	"\x18subscription_client_info\x18\x01 \x03(\v2\x1b.GnmiSubscriptionClientInfoR\x16subscriptionClientInfo\x12M\n" +
	"\x17get_request_timing_info\x18\x02 \x03(\v2\x16.GnmiRequestTimingInfoR\x14getRequestTimingInfo\x12,\n" +
	"\vdb_counters\x18\x03 \x01(\v2\v.DbCountersR\n" +
	"dbCounters\x12%\n" +
	"\x0enum_goroutines\x18\x04 \x01(\rR\rnumGoroutines\x12<\n" +
	"\x11go_runtime_metric\x18\x05 \x03(\v2\x10.GoRuntimeMetricR\x0fgoRuntimeMetric\x12Q\n" +
	"\x18connection_manager_stats\x18\x06 \x01(\v2\x17.ConnectionManagerStatsR\x16connectionManagerStats\x12M\n" +
	"\x17set_request_timing_info\x18\a \x03(\v2\x16.GnmiRequestTimingInfoR\x14setRequestTimingInfoB\x0eP\x01Z\n" +
	"gnmi.sonicb\x06proto3"

var (
	file_gnmi_sonic_umf_debug_info_proto_rawDescOnce sync.Once
	file_gnmi_sonic_umf_debug_info_proto_rawDescData []byte
)

func file_gnmi_sonic_umf_debug_info_proto_rawDescGZIP() []byte {
	file_gnmi_sonic_umf_debug_info_proto_rawDescOnce.Do(func() {
		file_gnmi_sonic_umf_debug_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gnmi_sonic_umf_debug_info_proto_rawDesc), len(file_gnmi_sonic_umf_debug_info_proto_rawDesc)))
	})
	return file_gnmi_sonic_umf_debug_info_proto_rawDescData
}

var file_gnmi_sonic_umf_debug_info_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gnmi_sonic_umf_debug_info_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gnmi_sonic_umf_debug_info_proto_goTypes = []any{
	(GnmiSubscriptionClientInfo_Mode)(0),    // 0: GnmiSubscriptionClientInfo.Mode
	(GnmiSubscriptionClientInfo_SubMode)(0), // 1: GnmiSubscriptionClientInfo.SubMode
	(*GnmiSubscriptionClientInfo)(nil),      // 2: GnmiSubscriptionClientInfo
	(*TickLatencyInfo)(nil),                 // 3: TickLatencyInfo
	(*GnmiRequestTimingInfo)(nil),           // 4: GnmiRequestTimingInfo
	(*DbCounters)(nil),                      // 5: DbCounters
	(*DbConnectionPoolStats)(nil),           // 6: DbConnectionPoolStats
	(*GoRuntimeMetric)(nil),                 // 7: GoRuntimeMetric
	(*ConnectionManagerStats)(nil),          // 8: ConnectionManagerStats
	(*UmfDebugInfo)(nil),                    // 9: UmfDebugInfo
	(*timestamppb.Timestamp)(nil),           // 10: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),             // 11: google.protobuf.Duration
}
var file_gnmi_sonic_umf_debug_info_proto_depIdxs = []int32{
	0,  // 0: GnmiSubscriptionClientInfo.subscription_mode:type_name -> GnmiSubscriptionClientInfo.Mode
	1,  // 1: GnmiSubscriptionClientInfo.subscription_sub_mode:type_name -> GnmiSubscriptionClientInfo.SubMode
	10, // 2: GnmiSubscriptionClientInfo.subscription_start:type_name -> google.protobuf.Timestamp
	10, // 3: GnmiSubscriptionClientInfo.sync_response_time:type_name -> google.protobuf.Timestamp
	3,  // 4: GnmiSubscriptionClientInfo.tick_latency_info:type_name -> TickLatencyInfo
	11, // 5: TickLatencyInfo.min_latency:type_name -> google.protobuf.Duration
	11, // 6: TickLatencyInfo.mean_latency:type_name -> google.protobuf.Duration
	11, // 7: TickLatencyInfo.max_latency:type_name -> google.protobuf.Duration
	10, // 8: GnmiRequestTimingInfo.start_time:type_name -> google.protobuf.Timestamp
	10, // 9: GnmiRequestTimingInfo.end_time:type_name -> google.protobuf.Timestamp
	6,  // 10: DbCounters.db_pool_stats:type_name -> DbConnectionPoolStats
	2,  // 11: UmfDebugInfo.subscription_client_info:type_name -> GnmiSubscriptionClientInfo
	4,  // 12: UmfDebugInfo.get_request_timing_info:type_name -> GnmiRequestTimingInfo
	5,  // 13: UmfDebugInfo.db_counters:type_name -> DbCounters
	7,  // 14: UmfDebugInfo.go_runtime_metric:type_name -> GoRuntimeMetric
	8,  // 15: UmfDebugInfo.connection_manager_stats:type_name -> ConnectionManagerStats
	4,  // 16: UmfDebugInfo.set_request_timing_info:type_name -> GnmiRequestTimingInfo
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_gnmi_sonic_umf_debug_info_proto_init() }
func file_gnmi_sonic_umf_debug_info_proto_init() {
	if File_gnmi_sonic_umf_debug_info_proto != nil {
		return
	}
	file_gnmi_sonic_umf_debug_info_proto_msgTypes[5].OneofWrappers = []any{
		(*GoRuntimeMetric_Uint64Val)(nil),
		(*GoRuntimeMetric_DoubleVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gnmi_sonic_umf_debug_info_proto_rawDesc), len(file_gnmi_sonic_umf_debug_info_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gnmi_sonic_umf_debug_info_proto_goTypes,
		DependencyIndexes: file_gnmi_sonic_umf_debug_info_proto_depIdxs,
		EnumInfos:         file_gnmi_sonic_umf_debug_info_proto_enumTypes,
		MessageInfos:      file_gnmi_sonic_umf_debug_info_proto_msgTypes,
	}.Build()
	File_gnmi_sonic_umf_debug_info_proto = out.File
	file_gnmi_sonic_umf_debug_info_proto_goTypes = nil
	file_gnmi_sonic_umf_debug_info_proto_depIdxs = nil
}
