load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "jsontest",
    srcs = [
        "dbutil.go",
        "jtest.go",
        "operation.go",
        "sub_operation.go",
    ],
    importpath = "github.com/sonic-net/sonic-gnmi/jsontest",
    visibility = ["//visibility:public"],
    deps = [
        "//sonic_db_config",
        "//transl_utils",
        "//translib/ocbinds",
        "//translib/path",
        "@com_github_golang_protobuf//proto",
        "@com_github_google_gnxi//utils/xpath",
        "@com_github_openconfig_gnmi//proto/gnmi",
        "@com_github_openconfig_gnmi//value",
        "@com_github_openconfig_ygot//ygot",
        "@com_github_openconfig_ygot//ytypes",
        "@com_github_redis_go_redis_v9//:go-redis",
        "@com_github_xeipuuv_gojsonschema//:gojsonschema",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_x_net//context",
    ],
)

alias(
    name = "go_default_library",
    actual = ":jsontest",
    visibility = ["//visibility:public"],
)
