load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "dialout_client_cli_lib",
    srcs = ["dialout_client_cli.go"],
    importpath = "github.com/sonic-net/sonic-gnmi/dialout/dialout_client_cli",
    visibility = ["//visibility:private"],
    deps = [
        "//dialout/dialout_client",
        "@com_github_golang_glog//:glog",
        "@com_github_openconfig_gnmi//proto/gnmi",
        "@org_golang_x_net//context",
    ],
)

go_binary(
    name = "dialout_client_cli",
    embed = [":dialout_client_cli_lib"],
    visibility = ["//visibility:public"],
)
