load("@rules_go//go:def.bzl", "go_library")
load("@rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

go_library(
    name = "qualification",
    embed = [":qualification_go_proto"],
    importpath = "github.com/sonic-net/sonic-gnmi/proto/gnoi/qualification",  #keep
    visibility = ["//visibility:public"],
)

alias(
    name = "go_default_library",
    actual = ":qualification",
    visibility = ["//visibility:public"],
)

proto_library(
    name = "gpins_gnoi_proto",
    srcs = ["packet_link_qualification.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_openconfig_gnoi//types:types_proto",
        "@googleapis//google/rpc:status_proto",
    ],
)

go_proto_library(
    name = "qualification_go_proto",
    compilers = ["@rules_go//proto:go_grpc"],
    importpath = "github.com/sonic-net/sonic-gnmi/proto/gnoi/qualification",  #keep
    proto = ":gpins_gnoi_proto",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_openconfig_gnoi//types",
        "@org_golang_google_genproto_googleapis_rpc//status",
    ],
)
