load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "pathz_authorizer",
    srcs = ["pathz_authorizer.go"],
    importpath = "github.com/sonic-net/sonic-gnmi/pathz_authorizer",
    visibility = ["//visibility:public"],
    deps = [
        "//gnmi_server/log",
        "@com_github_golang_glog//:glog",
        "@com_github_golang_protobuf//proto",
        "@com_github_openconfig_gnmi//proto/gnmi",
        "@com_github_openconfig_gnsi//pathz",
    ],
)

go_test(
    name = "pathz_authorizer_test",
    srcs = ["pathz_authorizer_test.go"],
    embed = [":pathz_authorizer"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_openconfig_gnmi//proto/gnmi",
        "@com_github_openconfig_gnsi//pathz",
    ],
)

alias(
    name = "go_default_library",
    actual = ":pathz_authorizer",
    visibility = ["//visibility:public"],
)
