load("@rules_go//go:def.bzl", "go_library")
load("@rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

#gazelle:ignore

go_library(
    name = "ocs",
    embed = [":ocs_go_proto"],
    importpath = "github.com/sonic-net/sonic-gnmi/proto/gnoi/ocs",  #keep
    visibility = ["//visibility:public"],
)

alias(
    name = "go_default_library",
    actual = ":ocs",
    visibility = ["//visibility:public"],
)

proto_library(
    name = "ocs_proto",
    srcs = [
        "lds.proto",
        "ocs.proto",
        "ocs_error.proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@googleapis//google/rpc:status_proto",
    ],
)

go_proto_library(
    name = "ocs_go_proto",
    compilers = ["@rules_go//proto:go_grpc"],
    importpath = "github.com/sonic-net/sonic-gnmi/proto/gnoi/ocs",  #keep
    proto = ":ocs_proto",
    visibility = ["//visibility:public"],
    deps = [
        "@org_golang_google_genproto_googleapis_rpc//status",
    ],
)
