// OCS represents a list of APIs that are used for interacting with Optical
// Circuit Switch (OCS).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.23.1
// source: proto/gnoi/ocs/ocs.proto

package ocs

import (
	context "context"
	status "google.golang.org/genproto/googleapis/rpc/status"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status1 "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Update_Action int32

const (
	Update_UNSPECIFIED Update_Action = 0
	Update_CONNECT     Update_Action = 1
	Update_DISCONNECT  Update_Action = 2
	Update_REPLACE     Update_Action = 3
)

// Enum value maps for Update_Action.
var (
	Update_Action_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "CONNECT",
		2: "DISCONNECT",
		3: "REPLACE",
	}
	Update_Action_value = map[string]int32{
		"UNSPECIFIED": 0,
		"CONNECT":     1,
		"DISCONNECT":  2,
		"REPLACE":     3,
	}
)

func (x Update_Action) Enum() *Update_Action {
	p := new(Update_Action)
	*p = x
	return p
}

func (x Update_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Update_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gnoi_ocs_ocs_proto_enumTypes[0].Descriptor()
}

func (Update_Action) Type() protoreflect.EnumType {
	return &file_proto_gnoi_ocs_ocs_proto_enumTypes[0]
}

func (x Update_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Update_Action.Descriptor instead.
func (Update_Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_gnoi_ocs_ocs_proto_rawDescGZIP(), []int{1, 0}
}

type Connection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	North *string `protobuf:"bytes,1,opt,name=north,proto3,oneof" json:"north,omitempty"`
	South *string `protobuf:"bytes,2,opt,name=south,proto3,oneof" json:"south,omitempty"`
}

func (x *Connection) Reset() {
	*x = Connection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gnoi_ocs_ocs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gnoi_ocs_ocs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_proto_gnoi_ocs_ocs_proto_rawDescGZIP(), []int{0}
}

func (x *Connection) GetNorth() string {
	if x != nil && x.North != nil {
		return *x.North
	}
	return ""
}

func (x *Connection) GetSouth() string {
	if x != nil && x.South != nil {
		return *x.South
	}
	return ""
}

type Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action     *Update_Action `protobuf:"varint,1,opt,name=action,proto3,enum=gpins.gnoi.Update_Action,oneof" json:"action,omitempty"`
	Connection *Connection    `protobuf:"bytes,2,opt,name=connection,proto3,oneof" json:"connection,omitempty"`
}

func (x *Update) Reset() {
	*x = Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gnoi_ocs_ocs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gnoi_ocs_ocs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_proto_gnoi_ocs_ocs_proto_rawDescGZIP(), []int{1}
}

func (x *Update) GetAction() Update_Action {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return Update_UNSPECIFIED
}

func (x *Update) GetConnection() *Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

type SetConnectionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target  *string   `protobuf:"bytes,1,opt,name=target,proto3,oneof" json:"target,omitempty"`
	Updates []*Update `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (x *SetConnectionsRequest) Reset() {
	*x = SetConnectionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gnoi_ocs_ocs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConnectionsRequest) ProtoMessage() {}

func (x *SetConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gnoi_ocs_ocs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConnectionsRequest.ProtoReflect.Descriptor instead.
func (*SetConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gnoi_ocs_ocs_proto_rawDescGZIP(), []int{2}
}

func (x *SetConnectionsRequest) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

func (x *SetConnectionsRequest) GetUpdates() []*Update {
	if x != nil {
		return x.Updates
	}
	return nil
}

type SetConnectionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success *bool                            `protobuf:"varint,1,opt,name=success,proto3,oneof" json:"success,omitempty"`
	Results []*SetConnectionsResponse_Result `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *SetConnectionsResponse) Reset() {
	*x = SetConnectionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gnoi_ocs_ocs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConnectionsResponse) ProtoMessage() {}

func (x *SetConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gnoi_ocs_ocs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConnectionsResponse.ProtoReflect.Descriptor instead.
func (*SetConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_gnoi_ocs_ocs_proto_rawDescGZIP(), []int{3}
}

func (x *SetConnectionsResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *SetConnectionsResponse) GetResults() []*SetConnectionsResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetConnectionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target *string `protobuf:"bytes,1,opt,name=target,proto3,oneof" json:"target,omitempty"`
}

func (x *GetConnectionsRequest) Reset() {
	*x = GetConnectionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gnoi_ocs_ocs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionsRequest) ProtoMessage() {}

func (x *GetConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gnoi_ocs_ocs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionsRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gnoi_ocs_ocs_proto_rawDescGZIP(), []int{4}
}

func (x *GetConnectionsRequest) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

type GetConnectionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Connection []*Connection `protobuf:"bytes,1,rep,name=connection,proto3" json:"connection,omitempty"`
}

func (x *GetConnectionsResponse) Reset() {
	*x = GetConnectionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gnoi_ocs_ocs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionsResponse) ProtoMessage() {}

func (x *GetConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gnoi_ocs_ocs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionsResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_gnoi_ocs_ocs_proto_rawDescGZIP(), []int{5}
}

func (x *GetConnectionsResponse) GetConnection() []*Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

type SetConnectionsResponse_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Update *Update        `protobuf:"bytes,1,opt,name=update,proto3,oneof" json:"update,omitempty"`
	Status *status.Status `protobuf:"bytes,2,opt,name=status,proto3,oneof" json:"status,omitempty"`
}

func (x *SetConnectionsResponse_Result) Reset() {
	*x = SetConnectionsResponse_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gnoi_ocs_ocs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetConnectionsResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConnectionsResponse_Result) ProtoMessage() {}

func (x *SetConnectionsResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gnoi_ocs_ocs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConnectionsResponse_Result.ProtoReflect.Descriptor instead.
func (*SetConnectionsResponse_Result) Descriptor() ([]byte, []int) {
	return file_proto_gnoi_ocs_ocs_proto_rawDescGZIP(), []int{3, 0}
}

func (x *SetConnectionsResponse_Result) GetUpdate() *Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *SetConnectionsResponse_Result) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_proto_gnoi_ocs_ocs_proto protoreflect.FileDescriptor

var file_proto_gnoi_ocs_ocs_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6e, 0x6f, 0x69, 0x2f, 0x6f, 0x63, 0x73,
	0x2f, 0x6f, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x70, 0x69, 0x6e,
	0x73, 0x2e, 0x67, 0x6e, 0x6f, 0x69, 0x1a, 0x17, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x72,
	0x70, 0x63, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x56, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a,
	0x05, 0x6e, 0x6f, 0x72, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05,
	0x6e, 0x6f, 0x72, 0x74, 0x68, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x73, 0x6f, 0x75, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x73, 0x6f, 0x75, 0x74, 0x68,
	0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6e, 0x6f, 0x72, 0x74, 0x68, 0x42, 0x08, 0x0a,
	0x06, 0x5f, 0x73, 0x6f, 0x75, 0x74, 0x68, 0x22, 0xdc, 0x01, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x19, 0x2e, 0x67, 0x70, 0x69, 0x6e, 0x73, 0x2e, 0x67, 0x6e, 0x6f, 0x69, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x3b, 0x0a, 0x0a, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x67, 0x70, 0x69, 0x6e, 0x73, 0x2e, 0x67, 0x6e, 0x6f, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x01, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x22, 0x43, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10, 0x01, 0x12,
	0x0e, 0x0a, 0x0a, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10, 0x02, 0x12,
	0x0b, 0x0a, 0x07, 0x52, 0x45, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x10, 0x03, 0x42, 0x09, 0x0a, 0x07,
	0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6d, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x88, 0x01, 0x01, 0x12, 0x2c, 0x0a, 0x07,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x67, 0x70, 0x69, 0x6e, 0x73, 0x2e, 0x67, 0x6e, 0x6f, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x8b, 0x02, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x88, 0x01, 0x01, 0x12,
	0x43, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x29, 0x2e, 0x67, 0x70, 0x69, 0x6e, 0x73, 0x2e, 0x67, 0x6e, 0x6f, 0x69, 0x2e, 0x53, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x1a, 0x80, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x2f, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x67, 0x70, 0x69, 0x6e, 0x73, 0x2e, 0x67, 0x6e, 0x6f, 0x69, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x48, 0x01, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01,
	0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x09, 0x0a, 0x07,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0x3f, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x22, 0x50, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36,
	0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x70, 0x69, 0x6e, 0x73, 0x2e, 0x67, 0x6e, 0x6f, 0x69, 0x2e,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xbb, 0x01, 0x0a, 0x03, 0x4f, 0x63, 0x73, 0x12, 0x59,
	0x0a, 0x0e, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x21, 0x2e, 0x67, 0x70, 0x69, 0x6e, 0x73, 0x2e, 0x67, 0x6e, 0x6f, 0x69, 0x2e, 0x53, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x70, 0x69, 0x6e, 0x73, 0x2e, 0x67, 0x6e, 0x6f, 0x69,
	0x2e, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x21, 0x2e, 0x67, 0x70,
	0x69, 0x6e, 0x73, 0x2e, 0x67, 0x6e, 0x6f, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x67, 0x70, 0x69, 0x6e, 0x73, 0x2e, 0x67, 0x6e, 0x6f, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6e,
	0x6f, 0x69, 0x2f, 0x6f, 0x63, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_gnoi_ocs_ocs_proto_rawDescOnce sync.Once
	file_proto_gnoi_ocs_ocs_proto_rawDescData = file_proto_gnoi_ocs_ocs_proto_rawDesc
)

func file_proto_gnoi_ocs_ocs_proto_rawDescGZIP() []byte {
	file_proto_gnoi_ocs_ocs_proto_rawDescOnce.Do(func() {
		file_proto_gnoi_ocs_ocs_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_gnoi_ocs_ocs_proto_rawDescData)
	})
	return file_proto_gnoi_ocs_ocs_proto_rawDescData
}

var file_proto_gnoi_ocs_ocs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_gnoi_ocs_ocs_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_gnoi_ocs_ocs_proto_goTypes = []interface{}{
	(Update_Action)(0),                    // 0: gpins.gnoi.Update.Action
	(*Connection)(nil),                    // 1: gpins.gnoi.Connection
	(*Update)(nil),                        // 2: gpins.gnoi.Update
	(*SetConnectionsRequest)(nil),         // 3: gpins.gnoi.SetConnectionsRequest
	(*SetConnectionsResponse)(nil),        // 4: gpins.gnoi.SetConnectionsResponse
	(*GetConnectionsRequest)(nil),         // 5: gpins.gnoi.GetConnectionsRequest
	(*GetConnectionsResponse)(nil),        // 6: gpins.gnoi.GetConnectionsResponse
	(*SetConnectionsResponse_Result)(nil), // 7: gpins.gnoi.SetConnectionsResponse.Result
	(*status.Status)(nil),                 // 8: google.rpc.Status
}
var file_proto_gnoi_ocs_ocs_proto_depIdxs = []int32{
	0, // 0: gpins.gnoi.Update.action:type_name -> gpins.gnoi.Update.Action
	1, // 1: gpins.gnoi.Update.connection:type_name -> gpins.gnoi.Connection
	2, // 2: gpins.gnoi.SetConnectionsRequest.updates:type_name -> gpins.gnoi.Update
	7, // 3: gpins.gnoi.SetConnectionsResponse.results:type_name -> gpins.gnoi.SetConnectionsResponse.Result
	1, // 4: gpins.gnoi.GetConnectionsResponse.connection:type_name -> gpins.gnoi.Connection
	2, // 5: gpins.gnoi.SetConnectionsResponse.Result.update:type_name -> gpins.gnoi.Update
	8, // 6: gpins.gnoi.SetConnectionsResponse.Result.status:type_name -> google.rpc.Status
	3, // 7: gpins.gnoi.Ocs.SetConnections:input_type -> gpins.gnoi.SetConnectionsRequest
	5, // 8: gpins.gnoi.Ocs.GetConnections:input_type -> gpins.gnoi.GetConnectionsRequest
	4, // 9: gpins.gnoi.Ocs.SetConnections:output_type -> gpins.gnoi.SetConnectionsResponse
	6, // 10: gpins.gnoi.Ocs.GetConnections:output_type -> gpins.gnoi.GetConnectionsResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_gnoi_ocs_ocs_proto_init() }
func file_proto_gnoi_ocs_ocs_proto_init() {
	if File_proto_gnoi_ocs_ocs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_gnoi_ocs_ocs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Connection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gnoi_ocs_ocs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gnoi_ocs_ocs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetConnectionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gnoi_ocs_ocs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetConnectionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gnoi_ocs_ocs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConnectionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gnoi_ocs_ocs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConnectionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gnoi_ocs_ocs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetConnectionsResponse_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_gnoi_ocs_ocs_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_proto_gnoi_ocs_ocs_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_proto_gnoi_ocs_ocs_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_proto_gnoi_ocs_ocs_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_proto_gnoi_ocs_ocs_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_proto_gnoi_ocs_ocs_proto_msgTypes[6].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_gnoi_ocs_ocs_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gnoi_ocs_ocs_proto_goTypes,
		DependencyIndexes: file_proto_gnoi_ocs_ocs_proto_depIdxs,
		EnumInfos:         file_proto_gnoi_ocs_ocs_proto_enumTypes,
		MessageInfos:      file_proto_gnoi_ocs_ocs_proto_msgTypes,
	}.Build()
	File_proto_gnoi_ocs_ocs_proto = out.File
	file_proto_gnoi_ocs_ocs_proto_rawDesc = nil
	file_proto_gnoi_ocs_ocs_proto_goTypes = nil
	file_proto_gnoi_ocs_ocs_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OcsClient is the client API for Ocs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OcsClient interface {
	SetConnections(ctx context.Context, in *SetConnectionsRequest, opts ...grpc.CallOption) (*SetConnectionsResponse, error)
	GetConnections(ctx context.Context, in *GetConnectionsRequest, opts ...grpc.CallOption) (*GetConnectionsResponse, error)
}

type ocsClient struct {
	cc grpc.ClientConnInterface
}

func NewOcsClient(cc grpc.ClientConnInterface) OcsClient {
	return &ocsClient{cc}
}

func (c *ocsClient) SetConnections(ctx context.Context, in *SetConnectionsRequest, opts ...grpc.CallOption) (*SetConnectionsResponse, error) {
	out := new(SetConnectionsResponse)
	err := c.cc.Invoke(ctx, "/gpins.gnoi.Ocs/SetConnections", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ocsClient) GetConnections(ctx context.Context, in *GetConnectionsRequest, opts ...grpc.CallOption) (*GetConnectionsResponse, error) {
	out := new(GetConnectionsResponse)
	err := c.cc.Invoke(ctx, "/gpins.gnoi.Ocs/GetConnections", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OcsServer is the server API for Ocs service.
type OcsServer interface {
	SetConnections(context.Context, *SetConnectionsRequest) (*SetConnectionsResponse, error)
	GetConnections(context.Context, *GetConnectionsRequest) (*GetConnectionsResponse, error)
}

// UnimplementedOcsServer can be embedded to have forward compatible implementations.
type UnimplementedOcsServer struct {
}

func (*UnimplementedOcsServer) SetConnections(context.Context, *SetConnectionsRequest) (*SetConnectionsResponse, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method SetConnections not implemented")
}
func (*UnimplementedOcsServer) GetConnections(context.Context, *GetConnectionsRequest) (*GetConnectionsResponse, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method GetConnections not implemented")
}

func RegisterOcsServer(s *grpc.Server, srv OcsServer) {
	s.RegisterService(&_Ocs_serviceDesc, srv)
}

func _Ocs_SetConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcsServer).SetConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpins.gnoi.Ocs/SetConnections",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcsServer).SetConnections(ctx, req.(*SetConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ocs_GetConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcsServer).GetConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpins.gnoi.Ocs/GetConnections",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcsServer).GetConnections(ctx, req.(*GetConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ocs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gpins.gnoi.Ocs",
	HandlerType: (*OcsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetConnections",
			Handler:    _Ocs_SetConnections_Handler,
		},
		{
			MethodName: "GetConnections",
			Handler:    _Ocs_GetConnections_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gnoi/ocs/ocs.proto",
}
