load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "swsscommon",
    srcs = ["empty.go"],
    importpath = "github.com/sonic-net/sonic-gnmi/swsscommon",
    embed = ["@sonic-swss-common//goext:swsscommon"],
    visibility = ["//visibility:public"],
)

alias(
    name = "swsscommon_consolidated_wrapper",
    actual = "@sonic-swss-common//goext:swsscommon_cgo_wrapper",
    visibility = ["//visibility:public"],
)

alias(
    name = "go_default_library",
    actual = ":swsscommon",
    visibility = ["//visibility:public"],
)
