ARG DEBIAN_VERSION=bullseye
FROM debian:${DEBIAN_VERSION}

# Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
  iproute2 \
  # rsyslog \
  iputils-ping \
  redis-tools \
  ntp \
  wget \
  procps \
  python3 \
  # supervisor \
  pip \
  python-is-python3

COPY *yang*1.0.73*.deb /
RUN apt install -y ./*.deb && rm -f ./*.deb


ENV DB_DIR=/var/run/redis/sonic-db/
RUN mkdir -p /var/run/redis/sonic-db/

# Location for platform.json
ENV PLATFORM_DIR=/usr/share/sonic/hwsku/
RUN mkdir -p /usr/share/sonic/hwsku/

WORKDIR /

RUN pip install Jinja2 netaddr pyyaml natsort lxml supervisor==4.2.1 supervisord-dependent-startup==1.4.0

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
        libdbus-1-3        \
        libdaemon0         \
        libjansson4        \
        libdbus-c++-1-0v5  \
        libatomic1          \
        libjemalloc2        \
        liblua5.1-0         \
        lua-bitop           \
        lua-cjson           \
        openssl             \
        libcurl3-gnutls     \
        libpython2.7        \
        net-tools           \
        traceroute          \
        ndisc6              \
        libopts25           \
        libedit2            \
        netbase             \
        cgroup-tools        \
 && apt-get clean -y      && \
    apt-get autoclean -y   && \
    apt-get autoremove -y && \
    rm -rf /debs

# RUN wget http://ftp.us.debian.org/debian/pool/main/r/rsyslog/rsyslog_8.2302.0-1~bpo11+1_amd64.deb
RUN wget http://ftp.us.debian.org/debian/pool/main/r/rsyslog/rsyslog_8.2102.0-2+deb11u1_amd64.deb
RUN apt install -y ./*.deb && rm -f ./*.deb
